version: "3.7"

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2
    networks:
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

networks:
  mongo-compose-network:
    driver: bridge